language: cpp

branches:
  only:
   - dev

before_script:
   - cmake --version
   - sudo add-apt-repository --yes ppa:dcthomp/smtk
   - sudo apt-get update -qq
   - sudo dpkg -r cmake cmake-data
   - sudo apt-get install cmake   # update cmake to 3.x
   - cmake --version
   - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ utopic main restricted universe multiverse'
   - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ utopic-updates main restricted universe multiverse'
   - sudo apt-get update -qq
   - sudo apt-get install freeglut3-dev
   - sudo apt-get install libxxf86vm-dev
   - sudo apt-get install libglew-dev
   - sudo apt-get install libglfw3-dev
   - sudo apt-get install xvfb    # for GLtests... not working though.

script:
   - cmake --version
   - mkdir build && cd build
   - cmake -DNO_TBB=1 -DNO_OMP=1 -DNO_CUDA=1 -DNO_OPENCL=1 -DNO_MAYA=1 -DNO_PTEX=1 -DNO_GLTESTS=1 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
   - make
   - make test

